### ISSUE TITLE
Error : Expression is ambiguous without more context

### ISSUE THREAD

**Issue by npvisual** [SwiftRex/CoreLocationMiddleware#18]
Been trying to use CoreLocationMiddleware in another application. However I am getting an error when I try to declare the middleware in a separate constant : 

```
let coreLocationMiddleware = CoreLocationMiddleware()
    .lift(
        inputActionMap: { (globalAction: AppAction) -> LocationAction? in
            return nil
        },
        outputActionMap: { (localAction: LocationAction) -> AppAction  in
            return AppAction.location(.updateLocation(true))
        } ,
        stateMap: { (state: AppState) -> LocationState in
            LocationState(
                authzStatus: state.authorizationStatus,
                location: state.currentLocation
            )
        }
    )
```

I get the following error in Xcode : 

> Type of expression is ambiguous without more context

Been trying to figure out where this comes from and avoid the ambiguous declarations by providing input / output types for each closure, but to no avail...

@luizmb any ideas what I am doing wrong here ?

**Comment by luizmb** [comment]
One thing that I usually do when I have type inference problems:
```swift
let coreLocationMiddleware: AnyMiddleware<MyLiftedInputAction, MyLiftedOutputAction, MyLiftedState> =
    originalMiddleware.lift(...).eraseToAnyMiddleware()
```

Start from there, it usually helps.

**Comment by npvisual** [comment]
Didn't help. Same message and no additional pointers. Gonna start from scratch again to see if I can figure out where this is coming from.

**Comment by npvisual** [comment]
Got it. The type of a parameter to create the `LocationState` object in the `stateMap` closure was wrong and, instead of pointing that out, Xcode just punts 🤦‍♂️and tells you that 

> Type of expression is ambiguous without more context

**Comment by luizmb** [comment]
Generics programming brings runtime errors to compile errors. That's great, explodes in your face, not on your users' hands. But... Xcode / SourceKit are not helpful at all. :(
